version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile  # Dockerfile deve estar no mesmo diretório do docker-compose.yml
    ports:
      - "3000:3000"
    depends_on:
      - mongo
    environment:
      MONGO_URI: "mongodb://mongo:27017/nestdb"  # Configuração para conectar ao MongoDB
    restart: always
    networks:
      - app-network

  mongo:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db  # Persistência de dados do MongoDB
    restart: always
    networks:
      - app-network

volumes:
  mongo-data:

networks:
  app-network:
    driver: bridge
