### list periodo
GET http://localhost:3000/periodo 

### get periodo
GET http://localhost:3000/periodo/1

### create periodo
POST http://localhost:3000/periodo 
Content-Type: application/json

{
    "name" : "Teste",
    "school_period" : "05 Periodo",
    "start_date" : "2000-01-01",
    "final_date" : "2001-02-02",
    "create_at" : "1999-12-30",
    "update_at" : "2001-05-10",
    "delete_at" : "2005-12-12"

}

### update periodo
PATCH http://localhost:3000/periodo/1
Content-Type: application/json

{
   "school_period" : "06 Periodo"
   
}



### delete periodo
DELETE http://localhost:3000/periodo